//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DongBoPhieuService.ASCService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ASCService.asc_serviceSoap")]
    public interface asc_serviceSoap {
        
        // CODEGEN: Generating message contract since element name ten_dn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePhieu", ReplyAction="*")]
        DongBoPhieuService.ASCService.UpdatePhieuResponse UpdatePhieu(DongBoPhieuService.ASCService.UpdatePhieuRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePhieu", ReplyAction="*")]
        System.Threading.Tasks.Task<DongBoPhieuService.ASCService.UpdatePhieuResponse> UpdatePhieuAsync(DongBoPhieuService.ASCService.UpdatePhieuRequest request);
        
        // CODEGEN: Generating message contract since element name ten_dn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateVOC", ReplyAction="*")]
        DongBoPhieuService.ASCService.UpdateVOCResponse UpdateVOC(DongBoPhieuService.ASCService.UpdateVOCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateVOC", ReplyAction="*")]
        System.Threading.Tasks.Task<DongBoPhieuService.ASCService.UpdateVOCResponse> UpdateVOCAsync(DongBoPhieuService.ASCService.UpdateVOCRequest request);
        
        // CODEGEN: Generating message contract since element name ten_dn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLichHen", ReplyAction="*")]
        DongBoPhieuService.ASCService.UpdateLichHenResponse UpdateLichHen(DongBoPhieuService.ASCService.UpdateLichHenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLichHen", ReplyAction="*")]
        System.Threading.Tasks.Task<DongBoPhieuService.ASCService.UpdateLichHenResponse> UpdateLichHenAsync(DongBoPhieuService.ASCService.UpdateLichHenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePhieuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePhieu", Namespace="http://tempuri.org/", Order=0)]
        public DongBoPhieuService.ASCService.UpdatePhieuRequestBody Body;
        
        public UpdatePhieuRequest() {
        }
        
        public UpdatePhieuRequest(DongBoPhieuService.ASCService.UpdatePhieuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePhieuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ten_dn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mat_khau;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int kieu_nhap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ma_phieu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string maphieu_mt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ma_kho;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ngay_tn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string gio_tn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int loai_tn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ngay_ht;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string gio_ht;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string nguoi_tn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ten_kh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ma_nkh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string di_dong;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string tel_1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string tel_2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string dia_chi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string ma_tinh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string ma_huyen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string ma_xa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string ma_ht;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string mota_loi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string serial;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ma_nh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string model;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public int kieu_phieu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string ma_bd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string ghi_chu;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public int trang_thai;
        
        public UpdatePhieuRequestBody() {
        }
        
        public UpdatePhieuRequestBody(
                    string ten_dn, 
                    string mat_khau, 
                    int kieu_nhap, 
                    string ma_phieu, 
                    string maphieu_mt, 
                    string ma_kho, 
                    string ngay_tn, 
                    string gio_tn, 
                    int loai_tn, 
                    string ngay_ht, 
                    string gio_ht, 
                    string nguoi_tn, 
                    string ten_kh, 
                    string ma_nkh, 
                    string di_dong, 
                    string tel_1, 
                    string tel_2, 
                    string dia_chi, 
                    string ma_tinh, 
                    string ma_huyen, 
                    string ma_xa, 
                    string ma_ht, 
                    string mota_loi, 
                    string serial, 
                    string ma_nh, 
                    string model, 
                    int kieu_phieu, 
                    string ma_bd, 
                    string ghi_chu, 
                    int trang_thai) {
            this.ten_dn = ten_dn;
            this.mat_khau = mat_khau;
            this.kieu_nhap = kieu_nhap;
            this.ma_phieu = ma_phieu;
            this.maphieu_mt = maphieu_mt;
            this.ma_kho = ma_kho;
            this.ngay_tn = ngay_tn;
            this.gio_tn = gio_tn;
            this.loai_tn = loai_tn;
            this.ngay_ht = ngay_ht;
            this.gio_ht = gio_ht;
            this.nguoi_tn = nguoi_tn;
            this.ten_kh = ten_kh;
            this.ma_nkh = ma_nkh;
            this.di_dong = di_dong;
            this.tel_1 = tel_1;
            this.tel_2 = tel_2;
            this.dia_chi = dia_chi;
            this.ma_tinh = ma_tinh;
            this.ma_huyen = ma_huyen;
            this.ma_xa = ma_xa;
            this.ma_ht = ma_ht;
            this.mota_loi = mota_loi;
            this.serial = serial;
            this.ma_nh = ma_nh;
            this.model = model;
            this.kieu_phieu = kieu_phieu;
            this.ma_bd = ma_bd;
            this.ghi_chu = ghi_chu;
            this.trang_thai = trang_thai;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePhieuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePhieuResponse", Namespace="http://tempuri.org/", Order=0)]
        public DongBoPhieuService.ASCService.UpdatePhieuResponseBody Body;
        
        public UpdatePhieuResponse() {
        }
        
        public UpdatePhieuResponse(DongBoPhieuService.ASCService.UpdatePhieuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePhieuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdatePhieuResult;
        
        public UpdatePhieuResponseBody() {
        }
        
        public UpdatePhieuResponseBody(int UpdatePhieuResult) {
            this.UpdatePhieuResult = UpdatePhieuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateVOCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateVOC", Namespace="http://tempuri.org/", Order=0)]
        public DongBoPhieuService.ASCService.UpdateVOCRequestBody Body;
        
        public UpdateVOCRequest() {
        }
        
        public UpdateVOCRequest(DongBoPhieuService.ASCService.UpdateVOCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateVOCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ten_dn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mat_khau;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int kieu_nhap;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ma_voc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ma_phieu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ngay_voc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string gio_voc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string noi_dung;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int kieu_voc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int muc_do;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int trang_thai;
        
        public UpdateVOCRequestBody() {
        }
        
        public UpdateVOCRequestBody(string ten_dn, string mat_khau, int kieu_nhap, string ma_voc, string ma_phieu, string user_name, string ngay_voc, string gio_voc, string noi_dung, int kieu_voc, int muc_do, int trang_thai) {
            this.ten_dn = ten_dn;
            this.mat_khau = mat_khau;
            this.kieu_nhap = kieu_nhap;
            this.ma_voc = ma_voc;
            this.ma_phieu = ma_phieu;
            this.user_name = user_name;
            this.ngay_voc = ngay_voc;
            this.gio_voc = gio_voc;
            this.noi_dung = noi_dung;
            this.kieu_voc = kieu_voc;
            this.muc_do = muc_do;
            this.trang_thai = trang_thai;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateVOCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateVOCResponse", Namespace="http://tempuri.org/", Order=0)]
        public DongBoPhieuService.ASCService.UpdateVOCResponseBody Body;
        
        public UpdateVOCResponse() {
        }
        
        public UpdateVOCResponse(DongBoPhieuService.ASCService.UpdateVOCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateVOCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateVOCResult;
        
        public UpdateVOCResponseBody() {
        }
        
        public UpdateVOCResponseBody(int UpdateVOCResult) {
            this.UpdateVOCResult = UpdateVOCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLichHenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLichHen", Namespace="http://tempuri.org/", Order=0)]
        public DongBoPhieuService.ASCService.UpdateLichHenRequestBody Body;
        
        public UpdateLichHenRequest() {
        }
        
        public UpdateLichHenRequest(DongBoPhieuService.ASCService.UpdateLichHenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateLichHenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ten_dn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string mat_khau;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ma_phieu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string noi_dung;
        
        public UpdateLichHenRequestBody() {
        }
        
        public UpdateLichHenRequestBody(string ten_dn, string mat_khau, string ma_phieu, string noi_dung) {
            this.ten_dn = ten_dn;
            this.mat_khau = mat_khau;
            this.ma_phieu = ma_phieu;
            this.noi_dung = noi_dung;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLichHenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLichHenResponse", Namespace="http://tempuri.org/", Order=0)]
        public DongBoPhieuService.ASCService.UpdateLichHenResponseBody Body;
        
        public UpdateLichHenResponse() {
        }
        
        public UpdateLichHenResponse(DongBoPhieuService.ASCService.UpdateLichHenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateLichHenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateLichHenResult;
        
        public UpdateLichHenResponseBody() {
        }
        
        public UpdateLichHenResponseBody(int UpdateLichHenResult) {
            this.UpdateLichHenResult = UpdateLichHenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface asc_serviceSoapChannel : DongBoPhieuService.ASCService.asc_serviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class asc_serviceSoapClient : System.ServiceModel.ClientBase<DongBoPhieuService.ASCService.asc_serviceSoap>, DongBoPhieuService.ASCService.asc_serviceSoap {
        
        public asc_serviceSoapClient() {
        }
        
        public asc_serviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public asc_serviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public asc_serviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public asc_serviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DongBoPhieuService.ASCService.UpdatePhieuResponse DongBoPhieuService.ASCService.asc_serviceSoap.UpdatePhieu(DongBoPhieuService.ASCService.UpdatePhieuRequest request) {
            return base.Channel.UpdatePhieu(request);
        }
        
        public int UpdatePhieu(
                    string ten_dn, 
                    string mat_khau, 
                    int kieu_nhap, 
                    string ma_phieu, 
                    string maphieu_mt, 
                    string ma_kho, 
                    string ngay_tn, 
                    string gio_tn, 
                    int loai_tn, 
                    string ngay_ht, 
                    string gio_ht, 
                    string nguoi_tn, 
                    string ten_kh, 
                    string ma_nkh, 
                    string di_dong, 
                    string tel_1, 
                    string tel_2, 
                    string dia_chi, 
                    string ma_tinh, 
                    string ma_huyen, 
                    string ma_xa, 
                    string ma_ht, 
                    string mota_loi, 
                    string serial, 
                    string ma_nh, 
                    string model, 
                    int kieu_phieu, 
                    string ma_bd, 
                    string ghi_chu, 
                    int trang_thai) {
            DongBoPhieuService.ASCService.UpdatePhieuRequest inValue = new DongBoPhieuService.ASCService.UpdatePhieuRequest();
            inValue.Body = new DongBoPhieuService.ASCService.UpdatePhieuRequestBody();
            inValue.Body.ten_dn = ten_dn;
            inValue.Body.mat_khau = mat_khau;
            inValue.Body.kieu_nhap = kieu_nhap;
            inValue.Body.ma_phieu = ma_phieu;
            inValue.Body.maphieu_mt = maphieu_mt;
            inValue.Body.ma_kho = ma_kho;
            inValue.Body.ngay_tn = ngay_tn;
            inValue.Body.gio_tn = gio_tn;
            inValue.Body.loai_tn = loai_tn;
            inValue.Body.ngay_ht = ngay_ht;
            inValue.Body.gio_ht = gio_ht;
            inValue.Body.nguoi_tn = nguoi_tn;
            inValue.Body.ten_kh = ten_kh;
            inValue.Body.ma_nkh = ma_nkh;
            inValue.Body.di_dong = di_dong;
            inValue.Body.tel_1 = tel_1;
            inValue.Body.tel_2 = tel_2;
            inValue.Body.dia_chi = dia_chi;
            inValue.Body.ma_tinh = ma_tinh;
            inValue.Body.ma_huyen = ma_huyen;
            inValue.Body.ma_xa = ma_xa;
            inValue.Body.ma_ht = ma_ht;
            inValue.Body.mota_loi = mota_loi;
            inValue.Body.serial = serial;
            inValue.Body.ma_nh = ma_nh;
            inValue.Body.model = model;
            inValue.Body.kieu_phieu = kieu_phieu;
            inValue.Body.ma_bd = ma_bd;
            inValue.Body.ghi_chu = ghi_chu;
            inValue.Body.trang_thai = trang_thai;
            DongBoPhieuService.ASCService.UpdatePhieuResponse retVal = ((DongBoPhieuService.ASCService.asc_serviceSoap)(this)).UpdatePhieu(inValue);
            return retVal.Body.UpdatePhieuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DongBoPhieuService.ASCService.UpdatePhieuResponse> DongBoPhieuService.ASCService.asc_serviceSoap.UpdatePhieuAsync(DongBoPhieuService.ASCService.UpdatePhieuRequest request) {
            return base.Channel.UpdatePhieuAsync(request);
        }
        
        public System.Threading.Tasks.Task<DongBoPhieuService.ASCService.UpdatePhieuResponse> UpdatePhieuAsync(
                    string ten_dn, 
                    string mat_khau, 
                    int kieu_nhap, 
                    string ma_phieu, 
                    string maphieu_mt, 
                    string ma_kho, 
                    string ngay_tn, 
                    string gio_tn, 
                    int loai_tn, 
                    string ngay_ht, 
                    string gio_ht, 
                    string nguoi_tn, 
                    string ten_kh, 
                    string ma_nkh, 
                    string di_dong, 
                    string tel_1, 
                    string tel_2, 
                    string dia_chi, 
                    string ma_tinh, 
                    string ma_huyen, 
                    string ma_xa, 
                    string ma_ht, 
                    string mota_loi, 
                    string serial, 
                    string ma_nh, 
                    string model, 
                    int kieu_phieu, 
                    string ma_bd, 
                    string ghi_chu, 
                    int trang_thai) {
            DongBoPhieuService.ASCService.UpdatePhieuRequest inValue = new DongBoPhieuService.ASCService.UpdatePhieuRequest();
            inValue.Body = new DongBoPhieuService.ASCService.UpdatePhieuRequestBody();
            inValue.Body.ten_dn = ten_dn;
            inValue.Body.mat_khau = mat_khau;
            inValue.Body.kieu_nhap = kieu_nhap;
            inValue.Body.ma_phieu = ma_phieu;
            inValue.Body.maphieu_mt = maphieu_mt;
            inValue.Body.ma_kho = ma_kho;
            inValue.Body.ngay_tn = ngay_tn;
            inValue.Body.gio_tn = gio_tn;
            inValue.Body.loai_tn = loai_tn;
            inValue.Body.ngay_ht = ngay_ht;
            inValue.Body.gio_ht = gio_ht;
            inValue.Body.nguoi_tn = nguoi_tn;
            inValue.Body.ten_kh = ten_kh;
            inValue.Body.ma_nkh = ma_nkh;
            inValue.Body.di_dong = di_dong;
            inValue.Body.tel_1 = tel_1;
            inValue.Body.tel_2 = tel_2;
            inValue.Body.dia_chi = dia_chi;
            inValue.Body.ma_tinh = ma_tinh;
            inValue.Body.ma_huyen = ma_huyen;
            inValue.Body.ma_xa = ma_xa;
            inValue.Body.ma_ht = ma_ht;
            inValue.Body.mota_loi = mota_loi;
            inValue.Body.serial = serial;
            inValue.Body.ma_nh = ma_nh;
            inValue.Body.model = model;
            inValue.Body.kieu_phieu = kieu_phieu;
            inValue.Body.ma_bd = ma_bd;
            inValue.Body.ghi_chu = ghi_chu;
            inValue.Body.trang_thai = trang_thai;
            return ((DongBoPhieuService.ASCService.asc_serviceSoap)(this)).UpdatePhieuAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DongBoPhieuService.ASCService.UpdateVOCResponse DongBoPhieuService.ASCService.asc_serviceSoap.UpdateVOC(DongBoPhieuService.ASCService.UpdateVOCRequest request) {
            return base.Channel.UpdateVOC(request);
        }
        
        public int UpdateVOC(string ten_dn, string mat_khau, int kieu_nhap, string ma_voc, string ma_phieu, string user_name, string ngay_voc, string gio_voc, string noi_dung, int kieu_voc, int muc_do, int trang_thai) {
            DongBoPhieuService.ASCService.UpdateVOCRequest inValue = new DongBoPhieuService.ASCService.UpdateVOCRequest();
            inValue.Body = new DongBoPhieuService.ASCService.UpdateVOCRequestBody();
            inValue.Body.ten_dn = ten_dn;
            inValue.Body.mat_khau = mat_khau;
            inValue.Body.kieu_nhap = kieu_nhap;
            inValue.Body.ma_voc = ma_voc;
            inValue.Body.ma_phieu = ma_phieu;
            inValue.Body.user_name = user_name;
            inValue.Body.ngay_voc = ngay_voc;
            inValue.Body.gio_voc = gio_voc;
            inValue.Body.noi_dung = noi_dung;
            inValue.Body.kieu_voc = kieu_voc;
            inValue.Body.muc_do = muc_do;
            inValue.Body.trang_thai = trang_thai;
            DongBoPhieuService.ASCService.UpdateVOCResponse retVal = ((DongBoPhieuService.ASCService.asc_serviceSoap)(this)).UpdateVOC(inValue);
            return retVal.Body.UpdateVOCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DongBoPhieuService.ASCService.UpdateVOCResponse> DongBoPhieuService.ASCService.asc_serviceSoap.UpdateVOCAsync(DongBoPhieuService.ASCService.UpdateVOCRequest request) {
            return base.Channel.UpdateVOCAsync(request);
        }
        
        public System.Threading.Tasks.Task<DongBoPhieuService.ASCService.UpdateVOCResponse> UpdateVOCAsync(string ten_dn, string mat_khau, int kieu_nhap, string ma_voc, string ma_phieu, string user_name, string ngay_voc, string gio_voc, string noi_dung, int kieu_voc, int muc_do, int trang_thai) {
            DongBoPhieuService.ASCService.UpdateVOCRequest inValue = new DongBoPhieuService.ASCService.UpdateVOCRequest();
            inValue.Body = new DongBoPhieuService.ASCService.UpdateVOCRequestBody();
            inValue.Body.ten_dn = ten_dn;
            inValue.Body.mat_khau = mat_khau;
            inValue.Body.kieu_nhap = kieu_nhap;
            inValue.Body.ma_voc = ma_voc;
            inValue.Body.ma_phieu = ma_phieu;
            inValue.Body.user_name = user_name;
            inValue.Body.ngay_voc = ngay_voc;
            inValue.Body.gio_voc = gio_voc;
            inValue.Body.noi_dung = noi_dung;
            inValue.Body.kieu_voc = kieu_voc;
            inValue.Body.muc_do = muc_do;
            inValue.Body.trang_thai = trang_thai;
            return ((DongBoPhieuService.ASCService.asc_serviceSoap)(this)).UpdateVOCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DongBoPhieuService.ASCService.UpdateLichHenResponse DongBoPhieuService.ASCService.asc_serviceSoap.UpdateLichHen(DongBoPhieuService.ASCService.UpdateLichHenRequest request) {
            return base.Channel.UpdateLichHen(request);
        }
        
        public int UpdateLichHen(string ten_dn, string mat_khau, string ma_phieu, string noi_dung) {
            DongBoPhieuService.ASCService.UpdateLichHenRequest inValue = new DongBoPhieuService.ASCService.UpdateLichHenRequest();
            inValue.Body = new DongBoPhieuService.ASCService.UpdateLichHenRequestBody();
            inValue.Body.ten_dn = ten_dn;
            inValue.Body.mat_khau = mat_khau;
            inValue.Body.ma_phieu = ma_phieu;
            inValue.Body.noi_dung = noi_dung;
            DongBoPhieuService.ASCService.UpdateLichHenResponse retVal = ((DongBoPhieuService.ASCService.asc_serviceSoap)(this)).UpdateLichHen(inValue);
            return retVal.Body.UpdateLichHenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DongBoPhieuService.ASCService.UpdateLichHenResponse> DongBoPhieuService.ASCService.asc_serviceSoap.UpdateLichHenAsync(DongBoPhieuService.ASCService.UpdateLichHenRequest request) {
            return base.Channel.UpdateLichHenAsync(request);
        }
        
        public System.Threading.Tasks.Task<DongBoPhieuService.ASCService.UpdateLichHenResponse> UpdateLichHenAsync(string ten_dn, string mat_khau, string ma_phieu, string noi_dung) {
            DongBoPhieuService.ASCService.UpdateLichHenRequest inValue = new DongBoPhieuService.ASCService.UpdateLichHenRequest();
            inValue.Body = new DongBoPhieuService.ASCService.UpdateLichHenRequestBody();
            inValue.Body.ten_dn = ten_dn;
            inValue.Body.mat_khau = mat_khau;
            inValue.Body.ma_phieu = ma_phieu;
            inValue.Body.noi_dung = noi_dung;
            return ((DongBoPhieuService.ASCService.asc_serviceSoap)(this)).UpdateLichHenAsync(inValue);
        }
    }
}
